Threads HW
TheHsoa/HW5.Threads.HomeWork pull request #1
Opened 2017-11-22 04:26 UTC by TheHsoa

Домашка по 5 уроку C# для тестировщиков "Threads":

Запустить N потоков, которые через случайные промежутки времени добавляют в очередь по одному числу от A до B. Запустить M потоков, которые забирают по одному числу из очереди и проверяют, является ли оно простое. Результат выводится на консоль в виде: “Число X простое” или “Число X не простое”. Числа N, M, A, B задаются как параметры запуска.

2017-12-08 05:35 UTC, pomadin requested changes
думаю, будет полезно доработать

2017-12-08 05:35 UTC, pomadin commented on Program.cs
> +
Тут конечно смешалось немножко все, и проверка полноты задаваемых параметров и проверка корректности задаваемого параметра и просто что-то не так. Я бы развел это, но советую найти и использовать одну из множества библиотек/пакетов, которые позволяют оперировать вх. параметрами для своего кругозора.

2017-12-08 05:35 UTC, pomadin commented on Program.cs
> +            var queue = new Queue<long>();
данная коллекция не потокобезопасная

2017-12-08 05:35 UTC, pomadin commented on Program.cs
> +            return a;
было бы неплохо весь код связанный с проверкой числа вынести в свой блок, например, реализовать метод расширение

2017-12-08 05:35 UTC, pomadin commented on Program.cs
> +        private static void AsyncTakeNumbersFromQueueInThreadAndDetermineIsPrime(Queue<long> queue, int m)
для точность, асинхронное поведение и многопоточное суть разные, почитай https://ru.stackoverflow.com/questions/445768/%D0%9C%D0%BD%D0%BE%D0%B3%D0%BE%D0%BF%D0%BE%D1%82%D0%BE%D1%87%D0%BD%D0%BE%D0%B5-vs-%D0%B0%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B5-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5

2017-12-08 05:35 UTC, pomadin commented on Program.cs
> +        private static void AsyncTakeNumbersFromQueueInThreadAndDetermineIsPrime(Queue<long> queue, int m)
имхо, выделение "запускатора" не тянет на самостоятельный метод, это больше часть программы которая не переиспользуема и неотчуждаема, либо тебе надо его параметризовать методом выполнения и количеством запусков, тогда - да, можно использовать дважды

2017-12-08 05:35 UTC, pomadin commented on Program.cs
> +        {
в твоем случае лаконичнее будет ```Task.Run``` вместо ```Task.Factory.StartNew```

2017-12-08 05:35 UTC, pomadin commented on Program.cs
> +                Thread.Sleep(Random.Next(1000));
временной лимит лучше вынести в константу класса и использовать ее, кстати, можно вынести и получение интервала засыпания

2017-12-08 05:35 UTC, pomadin commented on Program.cs
> +            AsyncAddRandomNumbersInQueue(queue, N);
по такому поведению, лучше определить очередь как поле статическое класса, а не передавать в контекст каждой задачи

2017-12-08 05:35 UTC, pomadin commented on Program.cs
> +            Parallel.For(0, m, x => { Task.Factory.StartNew(() => TakeNumberFromQueueAndDetermineIsPrime(queue)); });
тут у тебя явное непонимание, что есть `Parallel.For`, так надо воспользоваться или `Parallel.For` или `Task.Factory.StartNew`, иначе перебор

2017-12-08 05:35 UTC, pomadin commented on Program.cs
> +                catch (InvalidOperationException e)
если это проверка на пустую очередь, то она сделана через исключение - что **зло**

2017-12-20 09:24 UTC, TheHsoa commented on Program.cs
> +            Parallel.For(0, m, x => { Task.Factory.StartNew(() => TakeNumberFromQueueAndDetermineIsPrime(queue)); });
Как я понимаю
Тут я пытаюсь "одновременно" запустить m потоков получения чисел из очереди

2017-12-20 09:27 UTC, TheHsoa commented on Program.cs
> +        private static void AsyncTakeNumbersFromQueueInThreadAndDetermineIsPrime(Queue<long> queue, int m)
Количество запусков здесь это количество потоков или количество проходов цикла вытаскивания числа из очереди?

2017-12-20 10:26 UTC, TheHsoa commented on Program.cs
> +                catch (InvalidOperationException e)
тут использовалась не потокобезопасная очередь, поэтому если бы была обычная проверка на длину очереди, то возможно очередь бы уже изменил кто то другой, в момент когда я к ней обращался и так же бы попал на exception

почему плохо использовать исключение в данной ситуации?

2018-02-04 12:12 UTC, TheHsoa commented on Program.cs
> +            Parallel.For(0, m, x => { Task.Factory.StartNew(() => TakeNumberFromQueueAndDetermineIsPrime(queue)); });
Сделал так, чтобы они быстрее стартовали

2018-02-13 08:46 UTC, pomadin commented
Правильно не лить packages/** в VCS.

2018-02-13 09:17 UTC, pomadin requested changes
Я бы доработал еще...

2018-02-13 09:17 UTC, pomadin commented on Calculating.cs
> +            var random = new Random(Guid.NewGuid().GetHashCode());
вариант несколько странный, обычно преследуют цель поддержать одну случайную последовательность на протяжении жизни всего приложения, т.е. new Random() должен быть вызван один раз и далее использоваться. т.е. проще сделать
`private readonly static Rnd = new Random(seed);`
ну и главное seed проще получить через DateTime.Now и его тики или еще что-то подобное, а на этапе отладке это меняется на фиксированное значение для воспроизводимости, но вот использование guid hash code, виже первый раз - слишком оригинально

2018-02-13 09:17 UTC, pomadin commented on Program.cs
> +            Parallel.For(0, m, x => { Task.Run(() => TakeNumberFromQueueAndDetermineIsPrime(queue)); });
повторюсь все-таки, а зачем распараллеленный запуск задач, само создание задачи (Task) ничего не стоит и не имеет смысла делать Parallel.For вообще

2018-02-13 09:17 UTC, pomadin commented on Program.cs
> +            Parallel.For(0, m, x => { Task.Run(() => TakeNumberFromQueueAndDetermineIsPrime(queue)); });
это наоборот только усугубит время запуска при больших значениях m, так как обладает куда большими накладными расходами чем последовательный запуск задач

2018-02-13 09:17 UTC, pomadin commented on Program.cs
> +        private static readonly Action<int> RandomSleepAction = x => Thread.Sleep(Random.Next(x));
а зачем пробрасывать константу для генерации ожидания? 
* тут или надо обеспечивать засыпание на случайное время () => Thread.Sleep(Random.Next(MaxSleepingTime ));
* или надо раскладывать на получение времени засыпания и самого засыпания
```
private static void Sleep(int wait) => Thread.Sleep(wait);
private static void GetWaitPeriod() => Random.Next(MaxSleepingTime);
```

2018-02-13 09:17 UTC, pomadin commented on Program.cs
> +        private static readonly Action<int> RandomSleepAction = x => Thread.Sleep(Random.Next(x));
кстати зачем там Action<>?

2018-02-13 09:17 UTC, pomadin commented on Program.cs
> +                queue.Enqueue(Random.Next(a, b));
обычно, порядок иной, основной функционал, а потом простой, но это не всегда

2018-02-13 09:17 UTC, pomadin commented on Program.cs
> +                MultithreadingAddRandomNumbersInQueue(queue, options.N, options.A, options.B);
имхо, проброс A/B лишний, легче пробросить функцию "работы" - добавления в очередь случайного числа, то есть тело задачи и отдельно запустить задачи проверки, что то вида
```
StartJobs(N, () => queue.Enqueue(Random.Next(a, b)));
StartJobs(M, () => /* проверка числа из очереди на простое */)
```
суть, есть реализации алгоритма и есть их "распараллеливание", где алгоритм само параметризован и не требуется проброс "левых" параметров в запускаторе

2018-02-13 09:17 UTC, pomadin commented on Program.cs
> +                MultithreadingAddRandomNumbersInQueue(queue, options.N, options.A, options.B);
Естественно логика засыпания это декоратор над телом переданной функции, т.е. что то вида
WithSleep(Action job) => () => { job(); Thread.Sleeep(...); }

2018-02-18 10:26 UTC, TheHsoa commented on Program.cs
> +        private static readonly Action<int> RandomSleepAction = x => Thread.Sleep(Random.Next(x));
Он там и не нужен)

2018-03-19 10:59 UTC, pomadin approved these changes

2018-03-19 10:59 UTC, pomadin commented on Program.cs
> +                TakeNumberFromQueueAndDetermineIsPrimeAction(queue).WithSleep().InfinityJob().StartJobs(options.M);
для красоты можно было тоже определить как enqueue - по месту, но так тоже ничего

2018-03-19 10:59 UTC, pomadin commented on Program.cs
> +                TakeNumberFromQueueAndDetermineIsPrimeAction(queue).WithSleep().InfinityJob().StartJobs(options.M);
LGTM

2018-03-19 12:43 UTC, merged